name: Reliable Call Transcription (1000+ Recordings)

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger
    inputs:
      target_date:
        description: 'Date to process (YYYY-MM-DD). Leave empty for yesterday.'
        required: false
        type: string

jobs:
  transcribe-calls:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hours
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run reliable transcription
      env:
        RC_CLIENT_ID: ${{ secrets.RC_CLIENT_ID }}
        RC_CLIENT_SECRET: ${{ secrets.RC_CLIENT_SECRET }}
        RC_JWT: ${{ secrets.RC_JWT }}
        GROQ_API_KEY_1: ${{ secrets.GROQ_API_KEY_1 }}
        GROQ_API_KEY_2: ${{ secrets.GROQ_API_KEY_2 }}
        GROQ_API_KEY_3: ${{ secrets.GROQ_API_KEY_3 }}
        GROQ_API_KEY_4: ${{ secrets.GROQ_API_KEY_4 }}
        GROQ_API_KEY_5: ${{ secrets.GROQ_API_KEY_5 }}
        GROQ_API_KEY_6: ${{ secrets.GROQ_API_KEY_6 }}
        TARGET_DATE: ${{ inputs.target_date }}
        # Ultra-conservative settings to avoid RC limits
        RC_RPS: 0.25
        RC_MEDIA_DELAY: 12
      run: |
        python reliable_processor.py
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: transcription-results-${{ github.run_number }}
        path: daily_recordings/
        retention-days: 30
        
    - name: Show summary
      if: always()
      run: |
        echo "=== TRANSCRIPTION COMPLETE ==="
        if [ -d "daily_recordings" ]; then
          echo "Results saved in daily_recordings/"
          find daily_recordings -name "*.json" -exec echo "Found: {}" \;
          if [ -f daily_recordings/*/summary.json ]; then
            echo "=== SUMMARY ==="
            cat daily_recordings/*/summary.json
          fi
        fi
